; ------------------------------------------------------------------------------------------------------
; Additional configuration files
; ------------------------------------------------------------------------------------------------------
[Include]

;------------------------------------------------------------------------------------------------------
[Constants]


;------------------------------------------------------------------------------------------------------
[Device]

; direct_mode: choose stereo output option based on hardware
;	tab - Top and Bottom
;	tab_reversed
;	sbs - Side by Side
;	sbs_reversed
;	interlaced
;	interlaced_reversed
;	checkerboard
;	checkerboard_reversed
;
;   katanga_vr - vr output to HelixVision.
;   nvidia_dx9 - works on latest drivers. Requires 3D Vision Driver. Requires game in exclusive fullscreen.
;	nvidia_dx11 - works up to driver 452.06. Requires 3D Vision Driver. Requires game in windowed mode.
;
direct_mode = sbs

fps_monitor_interval = 1
show_fps_monitor = false
; fps_show_hide = no_modifiers VK_F5


; Asynchronous shader_regex_patch_mode uses a hyperscan/chimera regex engine that can be 5x faster than pcre2.
; The async modes avoid the insane stutter/lockups when using shader regex, instead we get delayed shader fixes 
; the first time a shader is encountered. (This means you will get graphic/stereo glitches now instead of stutter.)
; shader_regex_patch_mode = 5 will be the best option for most games (broken shaders are more quickly resolved), but 
; there are currently issues with games that load the entire shader set on launch (e.g Batman Arkham Knight), where 
; unacceptable launch delays can occur in mode 5, therefore mode 4 is the default.
;  shader_regex_patch_mode = 0; //synchronous pcre2 regex applied on first draw (this was the existing default value)
;  shader_regex_patch_mode = 1; //synchronous pcre2 regex applied on shader creation (this was an existing alternative)
;  shader_regex_patch_mode = 2; //pcre2 regex will be applied at the first draw on a background thread and the patched shader picked up once cached to disk at some future draw
;  shader_regex_patch_mode = 3; //pcre2 regex will be applied at shader creation on a background thread and the patched shader picked up once cached to disk at some future draw
;  shader_regex_patch_mode = 4; //chimera (falling back to pcre2 for certain patterns) regex will be applied at first draw on a background thread and the patched shader picked up once cached to disk at some future draw (this is the new default value)
;  shader_regex_patch_mode = 5; //chimera (falling back to pcre2 for certain patterns) regex will be applied at shader creation on a background thread and the patched shader picked up once cached to disk at some future draw

shader_regex_patch_mode = 4

; Variable shader_regex_thread_pool_num, which controls the number threads we use in the background for async regex.
; shader_regex_thread_pool_num doesn't seem to make much difference in the chimera modes, but a higher number of threads 
; will speed up shader resolution in the pcre2 modes at the cost of increased stutter.
;  shader_regex_thread_pool_num = -1 (the thread_pool object is from the boost library, and setting it to -1 will let boost pick the number of threads.)
;  shader_regex_thread_pool_num = 0 (geo-11 will decide the number of threads in the thread_pool based on cpu count.)
;  shader_regex_thread_pool_num = n (Any other value will override. )

shader_regex_thread_pool_num = -1


matrix_analyzer = 1
auto_detect_depth_buffer = 1
resolve_msaa_depth_buffers = 1
preserve_depth_buffers = 1
dm_deferred_context_queue_per_eye = 0
repeat_command_list_depth_buffer_stats = 0


;------------------------------------------------------------------------------------------------------
[Stereo]
dm_stereo_enabled = 1
dm_convergence = 0.6
dm_separation = 100
dm_hud_detection = 0
;dm_hud_depth_override = -1.0
dm_auto_convergence = 1
dm_auto_convergence_uav_buffer_updates = 1
dm_hud_depth_max_offset_in = 0.002

dm_min_convergence = 0.6
dm_max_convergence_soft = 6.0
dm_max_convergence_hard = 7.0
dm_popout_bias = 0.005
dm_slow_convergence_rate = 8.0
dm_slow_convergence_threshold_near = 0.0
dm_slow_convergence_threshold_far = 0.0
dm_instant_convergence_threshold = 4.0
dm_anti_judder_threshold = 0.5
dm_auto_convergence_hud_enabled = 1
dm_auto_convergence_hud_timeout = 2.0
dm_warn_no_z_buffer = 1
dm_patching_mode = 0
dm_auto_scissor_rect = 0
dm_auto_convergence_post_present = 0

dm_min_convergence_absolute_override = 0.6
dm_max_convergence_soft_absolute_override = 4.0
dm_max_convergence_hard_absolute_override = 6.0
dm_slow_convergence_rate_absolute_override = 9.0
dm_slow_convergence_threshold_near_absolute_override = 0.001
dm_slow_convergence_threshold_far_absolute_override= 0.001
dm_instant_convergence_threshold_absolute_override= 9991.2
dm_anti_judder_threshold_absolute_override= 0.02

popout_conv_step_up_multi = 1.01
popout_conv_step_down_multi = 0.99

;------------------------------------------------------------------------------------------------------
; Settings for GPU manipulations.
; Render settings override
;------------------------------------------------------------------------------------------------------
[Rendering]
override_directory_dm=ShaderFixesDM
dm_auto_patch_failure_path = DMAutoPatchFailures
dm_auto_patch_cache_path = DMAutoPatchCache
dm_auto_patch_cache_auto_scissor_path = AutoScissor
dm_auto_patch_cache_hud_path = Hud

; Automatically patched shaders will be written here if caching is enabled.
cache_directory_dm=ShaderCacheDM

;------------------------------------------------------------------------------------------------------
; Stereo hot keys management and settings
;------------------------------------------------------------------------------------------------------
[Constants]

global $increaseconvergence = 0
global $increaseconvergencefast = 1.05
global $increaseconvergencespeed = 0
global $increaseconvergencetime = -1

global $decreaseconvergence = 0
global $decreaseconvergencefast = 0.95
global $decreaseconvergencespeed = 0
global $decreaseconvergencetime = -1

global $increaseseparation = 0
global $increaseseparationspeed = 0
global $increaseseparationtime = -1

global $decreaseseparation = 0
global $decreaseseparationspeed = 0
global $decreaseseparationtime = -1

global $showoverlaystereoparams = 0
global $hideoverlaystereoparamstime = -1

global $increaseconvergencetransition = 1
global $decreaseconvergencetransition = 1
global $increaseseparationtransition = 1
global $decreaseseparationtransition = 1

global $adj_sep = -1
global $adj_conv = -1

[PresetIncreaseConvergenceSlow]
condition = ($increaseconvergence == 1 && $increaseconvergencespeed == 0 && autoconvergence_enabled == 0 && $increaseconvergencetransition == 1)
$adj_conv = convergence + 0.01
convergence = convergence + 0.01
$increaseconvergencetransition = 0
transition = 100
transition_type = linear

[PresetIncreaseConvergenceFast]
condition = ($increaseconvergence == 1  && $increaseconvergencespeed == 1 && autoconvergence_enabled == 0 && $increaseconvergencetransition == 1)
$adj_conv = convergence * $increaseconvergencefast
convergence = convergence * $increaseconvergencefast
$increaseconvergencetransition = 0
transition = 50
transition_type = cosine

[PresetDecreaseConvergenceSlow]
condition = ($decreaseconvergence == 1 && $decreaseconvergencespeed == 0 && autoconvergence_enabled == 0 && convergence > 0.01 && $decreaseconvergencetransition == 1)
$adj_conv = convergence - 0.01
convergence = convergence - 0.01
$decreaseconvergencetransition = 0
transition = 100
transition_type = linear

[PresetDecreaseConvergenceFast]
condition = ($decreaseconvergence == 1 && $decreaseconvergencespeed == 1 && autoconvergence_enabled == 0 && convergence > 0.01 && $decreaseconvergencetransition == 1)
$adj_conv = convergence * $decreaseconvergencefast
convergence = convergence * $decreaseconvergencefast
$decreaseconvergencetransition = 0
transition = 50
transition_type = cosine

[PresetIncreaseSeparationSlow]
condition = ($increaseSeparation == 1 && $increaseseparationspeed == 0 && $increaseseparationtransition == 1)
$adj_sep = separation + 1
separation = separation + 1
$increaseseparationtransition = 0
transition = 100
transition_type = linear

[PresetIncreaseSeparationFast]
condition = ($increaseSeparation == 1 && $increaseseparationspeed == 1 && $increaseseparationtransition == 1)
$adj_sep = separation + 1
separation = separation + 1
$increaseseparationtransition = 0
transition = 25
transition_type = linear

[PresetDecreaseSeparationSlow]
condition = ($decreaseseparation == 1 && $decreaseseparationspeed == 0 && $decreaseseparationtransition == 1)
$adj_sep = separation - 1
separation = separation - 1
$decreaseseparationtransition = 0
transition = 100
transition_type = linear

[PresetDecreaseSeparationFast]
condition = ($decreaseseparation == 1 && $decreaseseparationspeed == 1 && $decreaseseparationtransition == 1)
$adj_sep = separation - 1
separation = separation - 1
$decreaseseparationtransition = 0
transition = 25
transition_type = linear

[Present]
if ($increaseconvergencetime != -1)
	if time - $increaseconvergencetime > 3.0
		$increaseconvergencespeed = 1
		$increaseconvergencefast = 1.05
	else if time - $increaseconvergencetime > 0.25
		$increaseconvergencespeed = 1
		$increaseconvergencefast = 1.01
	else
		$increaseconvergencespeed = 0
	endif
endif
if ((convergence * $increaseconvergencefast) - convergence) < 0.01
	$increaseconvergencefast = (convergence + 0.01) / convergence
endif

if ($increaseconvergencetransition == 0)
	$increaseconvergencetransition = 1
endif
preset = PresetIncreaseConvergenceSlow
preset = PresetIncreaseConvergenceFast

if ($decreaseconvergencetime != -1)
	if time - $decreaseconvergencetime > 3.0
		$decreaseconvergencespeed = 1
		$decreaseconvergencefast = 0.95
	else if time - $decreaseconvergencetime > 0.25
		$decreaseconvergencespeed = 1
		$decreaseconvergencefast = 0.99
	else
		$decreaseconvergencespeed = 0
	endif
endif
if (convergence - (convergence * $decreaseconvergencefast)) < 0.01
	$decreaseconvergencefast = (convergence - 0.01) / convergence
endif
if ($decreaseconvergencetransition == 0)
	$decreaseconvergencetransition = 1
endif

preset = PresetDecreaseConvergenceSlow
preset = PresetDecreaseConvergenceFast

if ($increaseseparationtime != -1)
	if time - $increaseseparationtime > 0.25
		$increaseseparationspeed = 1
	else
		$increaseseparationspeed = 0
	endif
endif
if ($increaseseparationtransition == 0)
	$increaseseparationtransition = 1
endif

preset = PresetIncreaseSeparationSlow
preset = PresetIncreaseSeparationFast

if ($decreaseseparationtime != -1)
	if time - $decreaseseparationtime > 0.25
		$decreaseseparationspeed = 1
	else
		$decreaseseparationspeed = 0
	endif
endif
if ($decreaseseparationtransition == 0)
	$decreaseseparationtransition = 1
endif

preset = PresetDecreaseSeparationSlow
preset = PresetDecreaseSeparationFast

if $showoverlaystereoparams
	show_stereo_params = 1
	$hideoverlaystereoparamstime = -1
else
	if $increaseSeparation || $decreaseseparation || (($increaseconvergence|| $decreaseconvergence) && !autoconvergence_enabled)
		show_stereo_params = 1
		$hideoverlaystereoparamstime = time
	else if $hideoverlaystereoparamstime == -1
		show_stereo_params = 0
	else if $hideoverlaystereoparamstime + 2.0 < time
		show_stereo_params = 0
		$hideoverlaystereoparamstime = -1
	endif
endif

[CommandListIncreaseConvergenceStart]
$increaseconvergence = 1
$increaseconvergencespeed = 0
$increaseconvergencetime = time

[CommandListIncreaseConvergenceStop]
$increaseconvergence = 0
$increaseconvergencespeed = 0
$increaseconvergencetime = -1

[CommandListIncreaseConvergence]
run = CommandListIncreaseConvergenceStart
post run = CommandListIncreaseConvergenceStop

[CommandListDecreaseConvergenceStart]
$decreaseconvergence = 1
$decreaseconvergencespeed = 0
$decreaseconvergencetime = time

[CommandListDecreaseConvergenceStop]
$decreaseconvergence = 0
$decreaseconvergencespeed = 0
$decreaseconvergencetime = -1

[CommandListDecreaseConvergence]
run = CommandListDecreaseConvergenceStart
post run = CommandListDecreaseConvergenceStop

[CommandListIncreaseSeparationStart]
$increaseseparation = 1
$increaseseparationspeed = 0
$increaseseparationtime = time

[CommandListIncreaseSeparationStop]
$increaseseparation = 0
$increaseseparationspeed = 0
$increaseseparationtime = -1

[CommandListIncreaseSeparation]
run = CommandListIncreaseSeparationStart
post run = CommandListIncreaseSeparationStop

[CommandListDecreaseSeparationStart]
$decreaseseparation = 1
$decreaseseparationspeed = 0
$decreaseseparationtime = time

[CommandListDecreaseSeparationStop]
$decreaseseparation = 0
$decreaseseparationspeed = 0
$decreaseseparationtime = -1

[CommandListDecreaseSeparation]
run = CommandListDecreaseSeparationStart
post run = CommandListDecreaseSeparationStop

[KeyToggleOverlayStereoParams]
Key = shift F6
type = toggle
$showoverlaystereoparams = 1

[KeyIncreaseConvergence]
Key = ctrl F6
type = hold
run = CommandListIncreaseConvergence

[KeyDecreaseConvergence]
Key = ctrl F5
type = hold
run = CommandListDecreaseConvergence

[KeyIncreaseSeparation]
Key = ctrl F4
type = hold
run = CommandListIncreaseSeparation

[KeyDecreaseSeparation]
Key = ctrl F3
type = hold
run = CommandListDecreaseSeparation

[KeySaveSettings]
Key = ctrl F7
run = CommandListSaveSettings

[CommandListSaveSettings]
if ($adj_sep == separation || $adj_conv == convergence)
	pre overlay_notice = Saved modified stereo values
endif
if ($adj_sep == separation)
	pre persist separation = $adj_sep
endif
if ($adj_conv == convergence)
	pre persist convergence = $adj_conv
endif